name: GitHub Actions Secret Example
on:
  push:
    branches: [ main ]
jobs:
  secrets-in-github-actions:
    runs-on: ${{ matrix.os }}

  # The Secret Actions GitHub example has three steps
  steps:
  # Show how to print unmasked GitHuh secrets to the console name: Step 1 - Echo out a GitHub Actions Secret to the logs
    - name: Step 1 - Echo out a GitHub Actions Secret to the logs
      run: |
        echo "The GitHub Action Secret will be masked: "
        echo $íf secrets.TEST_SECRET }}
        echo "Trick to echo GitHub Actions Secret: "
        echo $í{secrets.TEST_SECRET}} | sed 's/./& /g'